cache: pip

language: python

matrix:
  include:
  - python: 3.5
    dist: xenial
    sudo: false
    env: DJANGO="2.1"
  - python: 3.5
    dist: xenial
    sudo: false
    env: DJANGO="2.2"

  - python: 3.6
    dist: xenial
    sudo: false
    env: DJANGO="2.1"
  - python: 3.6
    dist: xenial
    sudo: false
    env: DJANGO="2.2"
  - python: 3.6
    dist: xenial
    sudo: false
    env: DJANGO="3.0"

  - python: 3.7
    dist: xenial
    sudo: true
    env: DJANGO="2.2"
  - python: 3.7
    dist: xenial
    sudo: true
    env: DJANGO="3.0"

addons:
  apt:
    packages:
      - libjpeg8
      - libjpeg8-dev

install:
  - pip install tox tox-travis codecov

script:
  - python3 -c "import sqlite3;print(sqlite3.sqlite_version)"
  - tox

notifications:
  irc:
    - "irc.freenode.org#django-wiki"

after_success:
  - codecov
